server:
  port: 8025
spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/teste
#    generate-unique-name: false
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
  jpa:
    show-sql: true # ADD p/ Hibernate
    properties:
      javax:
        persistence:
          validation:
            mode: none
      hibernate: # ADD p/ Hibernate
        jdbc:
          lob:
            non_contextual_creation: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop

