server:
  port: 8025
spring:
  profiles:
    active: dev
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
      hibernate:
        format_sql: false
    show-sql: true
--- # Profile DEV
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    generate-unique-name: false
    url: jdbc:h2:mem:pw25s-dev
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
--- # Profile Prod
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/teste
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
